--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Sep 29 2018 14:23
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Drop Table    : 'GenericType'   
--
DROP TABLE GenericType
GO
--
-- Drop Table    : 'PersonType'   
--
DROP TABLE PersonType
GO
--
-- Drop Table    : 'Note'   
--
DROP TABLE Note
GO
--
-- Drop Table    : 'EmailAddress'   
--
DROP TABLE EmailAddress
GO
--
-- Drop Table    : 'ContactInfo'   
--
DROP TABLE ContactInfo
GO
--
-- Drop Table    : 'Address'   
--
DROP TABLE Address
GO
--
-- Drop Table    : 'City'   
--
DROP TABLE City
GO
--
-- Drop Table    : 'Person'   
--
DROP TABLE Person
GO
