--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Sep 29 2018 14:23
-- Script Generated by Database Design Studio 2.21.3 
--



--
-- Create Table    : 'Person'   
-- fullName        :  
--
CREATE TABLE Person (
    fullName       CHAR NOT NULL,
CONSTRAINT pk_Person PRIMARY KEY CLUSTERED (fullName))
GO

--
-- Create Table    : 'City'   
-- cityName        :  
-- zipCode         :  
--
CREATE TABLE City (
    cityName       CHAR(1) NOT NULL,
    zipCode        CHAR(1) NOT NULL,
CONSTRAINT pk_City PRIMARY KEY CLUSTERED (cityName,zipCode))
GO

--
-- Create Table    : 'Address'   
-- streetAddress   :  
-- countryRegion   :  
-- cityName        :  (references City.cityName)
-- zipCode         :  (references City.zipCode)
-- fullName        :  (references Person.fullName)
--
CREATE TABLE Address (
    streetAddress  CHAR(1) NOT NULL UNIQUE,
    countryRegion  CHAR(1) NOT NULL,
    cityName       CHAR(1) NOT NULL,
    zipCode        CHAR(1) NOT NULL,
    fullName       CHAR NOT NULL,
CONSTRAINT pk_Address PRIMARY KEY CLUSTERED (streetAddress,countryRegion),
CONSTRAINT fk_Address2 FOREIGN KEY (cityName,zipCode)
    REFERENCES City (cityName,zipCode)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
CONSTRAINT fk_Address3 FOREIGN KEY (fullName)
    REFERENCES Person (fullName)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'ContactInfo'   
-- company         :  
-- phoneNumber     :  
-- fullName        :  (references Person.fullName)
--
CREATE TABLE ContactInfo (
    company        CHAR NOT NULL,
    phoneNumber    BIGINT NOT NULL UNIQUE,
    fullName       CHAR NOT NULL,
CONSTRAINT pk_ContactInfo PRIMARY KEY CLUSTERED (company,phoneNumber),
CONSTRAINT fk_ContactInfo FOREIGN KEY (fullName)
    REFERENCES Person (fullName)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'EmailAddress'   
-- email           :  
-- fullName        :  (references Person.fullName)
--
CREATE TABLE EmailAddress (
    email          CHAR(1) NOT NULL UNIQUE,
    fullName       CHAR NULL,
CONSTRAINT pk_EmailAddress PRIMARY KEY CLUSTERED (email),
CONSTRAINT fk_EmailAddress FOREIGN KEY (fullName)
    REFERENCES Person (fullName)
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Note'   
-- noteId          :  
-- fullName        :  (references Person.fullName)
--
CREATE TABLE Note (
    noteId         BIGINT NOT NULL,
    fullName       CHAR NULL,
CONSTRAINT pk_Note PRIMARY KEY CLUSTERED (noteId),
CONSTRAINT fk_Note FOREIGN KEY (fullName)
    REFERENCES Person (fullName)
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'PersonType'   
-- type            :  
-- fullName        :  (references Person.fullName)
--
CREATE TABLE PersonType (
    type           CHAR NOT NULL,
    fullName       CHAR NOT NULL,
CONSTRAINT pk_PersonType PRIMARY KEY CLUSTERED (type),
CONSTRAINT fk_PersonType FOREIGN KEY (fullName)
    REFERENCES Person (fullName)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'GenericType'   
-- type            :  
-- streetAddress   :  (references Address.streetAddress)
-- countryRegion   :  (references Address.countryRegion)
-- company         :  (references ContactInfo.company)
-- phoneNumber     :  (references ContactInfo.phoneNumber)
--
CREATE TABLE GenericType (
    type           CHAR NOT NULL,
    streetAddress  CHAR(1) NULL,
    countryRegion  CHAR(1) NULL,
    company        CHAR NULL,
    phoneNumber    BIGINT NULL,
CONSTRAINT pk_GenericType PRIMARY KEY CLUSTERED (type),
CONSTRAINT fk_GenericType FOREIGN KEY (streetAddress,countryRegion)
    REFERENCES Address (streetAddress,countryRegion)
    ON UPDATE CASCADE,
CONSTRAINT fk_GenericType2 FOREIGN KEY (company,phoneNumber)
    REFERENCES ContactInfo (company,phoneNumber)
    ON UPDATE CASCADE)
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON Person TO public
GO
GRANT ALL ON City TO public
GO
GRANT ALL ON Address TO public
GO
GRANT ALL ON ContactInfo TO public
GO
GRANT ALL ON EmailAddress TO public
GO
GRANT ALL ON Note TO public
GO
GRANT ALL ON PersonType TO public
GO
GRANT ALL ON GenericType TO public
GO

