--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Sep 28 2018 16:36
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Create Database : 'db_name'   
--
SET NOCOUNT      ON
SET DATEFORMAT   dmy
 
USE master
 
GO
 
DECLARE @dttm VARCHAR(55)
SELECT  @dttm=CONVERT(VARCHAR,GETDATE(),3)
RAISERROR('BEGINNING BATCH BUILD AT %s ....',1,1,@dttm) WITH NOWAIT
 
IF EXISTS (SELECT NAME FROM SYSDATABASES WHERE NAME='db_name')
    DROP DATABASE db_name
 
GO
 
--IF (CHARINDEX('4.2', @@VERSION) > 0 OR
--    CHARINDEX('6.0', @@VERSION) > 0 OR
--    CHARINDEX('6.5', @@VERSION) > 0)
--    CREATE DATABASE db_name
--        ON MASTER = 1
--        LOG ON MASTER = 1
--ELSE
    CREATE DATABASE db_name
GO


--
-- Create Table    : 'Address'   
-- addressType     :  
-- streetAddress   :  
-- countryRegion   :  
-- zipCode         :  
-- cityName        :  
--
CREATE TABLE Address (
    addressType    CHAR(1) NOT NULL,
    streetAddress  CHAR(1) NOT NULL,
    countryRegion  CHAR(1) NOT NULL,
    zipCode        CHAR(1) NOT NULL,
    cityName       CHAR(1) NOT NULL,
CONSTRAINT pk_Address PRIMARY KEY CLUSTERED (addressType,streetAddress,countryRegion,zipCode,cityName))
GO

--
-- Create Table    : 'ContactInfo'   
-- company         :  
-- phoneNumber     :  
--
CREATE TABLE ContactInfo (
    company        CHAR NOT NULL,
    phoneNumber    CHAR NOT NULL,
CONSTRAINT pk_ContactInfo PRIMARY KEY CLUSTERED (company,phoneNumber))
GO

--
-- Create Table    : 'Person'   
-- fullName        :  
-- type            :  
-- addressType     :  (references Address.addressType)
-- streetAddress   :  (references Address.streetAddress)
-- countryRegion   :  (references Address.countryRegion)
-- zipCode         :  (references Address.zipCode)
-- cityName        :  (references Address.cityName)
-- company         :  (references ContactInfo.company)
-- phoneNumber     :  (references ContactInfo.phoneNumber)
--
CREATE TABLE Person (
    fullName       CHAR NOT NULL,
    type           BIGINT NOT NULL UNIQUE,
    addressType    CHAR(1) NOT NULL,
    streetAddress  CHAR(1) NOT NULL,
    countryRegion  CHAR(1) NOT NULL,
    zipCode        CHAR(1) NOT NULL,
    cityName       CHAR(1) NOT NULL,
    company        CHAR NOT NULL,
    phoneNumber    CHAR NOT NULL,
CONSTRAINT pk_Person PRIMARY KEY CLUSTERED (fullName,type),
CONSTRAINT fk_Person FOREIGN KEY (addressType,streetAddress,countryRegion,zipCode,cityName)
    REFERENCES Address (addressType,streetAddress,countryRegion,zipCode,cityName)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_Person2 FOREIGN KEY (company,phoneNumber)
    REFERENCES ContactInfo (company,phoneNumber)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'EmailAddress'   
-- email           :  
-- fullName        :  (references Person.fullName)
-- type            :  (references Person.type)
--
CREATE TABLE EmailAddress (
    email          CHAR(1) NOT NULL UNIQUE,
    fullName       CHAR NULL,
    type           BIGINT NULL,
CONSTRAINT pk_EmailAddress PRIMARY KEY CLUSTERED (email),
CONSTRAINT fk_EmailAddress FOREIGN KEY (fullName,type)
    REFERENCES Person (fullName,type)
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'AA'   
-- fullName        :  (references Person.fullName)
-- type            :  (references Person.type)
-- addressType     :  (references Address.addressType)
-- streetAddress   :  (references Address.streetAddress)
-- countryRegion   :  (references Address.countryRegion)
-- zipCode         :  (references Address.zipCode)
-- cityName        :  (references Address.cityName)
--
CREATE TABLE AA (
    fullName       CHAR NOT NULL,
    type           BIGINT NOT NULL,
    addressType    CHAR(1) NOT NULL,
    streetAddress  CHAR(1) NOT NULL,
    countryRegion  CHAR(1) NOT NULL,
    zipCode        CHAR(1) NOT NULL,
    cityName       CHAR(1) NOT NULL,
CONSTRAINT pk_AA PRIMARY KEY CLUSTERED (fullName,type,addressType,streetAddress,countryRegion,zipCode,cityName),
CONSTRAINT fk_AA FOREIGN KEY (fullName,type)
    REFERENCES Person (fullName,type)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_AA2 FOREIGN KEY (addressType,streetAddress,countryRegion,zipCode,cityName)
    REFERENCES Address (addressType,streetAddress,countryRegion,zipCode,cityName)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'ACI'   
-- fullName        :  (references Person.fullName)
-- type            :  (references Person.type)
-- company         :  (references ContactInfo.company)
-- phoneNumber     :  (references ContactInfo.phoneNumber)
--
CREATE TABLE ACI (
    fullName       CHAR NOT NULL,
    type           BIGINT NOT NULL,
    company        CHAR NOT NULL,
    phoneNumber    CHAR NOT NULL,
CONSTRAINT pk_ACI PRIMARY KEY CLUSTERED (fullName,type,company,phoneNumber),
CONSTRAINT fk_ACI FOREIGN KEY (fullName,type)
    REFERENCES Person (fullName,type)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_ACI2 FOREIGN KEY (company,phoneNumber)
    REFERENCES ContactInfo (company,phoneNumber)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Note'   
-- noteId          :  
-- fullName        :  (references Person.fullName)
-- type            :  (references Person.type)
--
CREATE TABLE Note (
    noteId         BIGINT NOT NULL,
    fullName       CHAR NULL,
    type           BIGINT NULL,
CONSTRAINT pk_Note PRIMARY KEY CLUSTERED (noteId),
CONSTRAINT fk_Note FOREIGN KEY (fullName,type)
    REFERENCES Person (fullName,type)
    ON UPDATE CASCADE)
GO

--
-- Permissions for: 'public'
--
--GRANT ALL ON Address TO public
--GO
--GRANT ALL ON ContactInfo TO public
--GO
--GRANT ALL ON Person TO public
--GO
--GRANT ALL ON EmailAddress TO public
--GO
--GRANT ALL ON AA TO public
--GO
--GRANT ALL ON ACI TO public
--GO
--GRANT ALL ON Note TO public
--GO

