--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Sep 28 2018 17:03
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Drop Database : 'db_name'   
--
USE master
GO
IF EXISTS (SELECT * FROM SYSDATABASES WHERE NAME='db_name')
    DROP DATABASE db_name
GO
