--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Oct 09 2018 14:14
-- Script Generated by Database Design Studio 2.21.3 
--



--
-- Create Table    : 'City'   
-- cityName        :  
-- zipCode         :  
-- cityId          :  
-- countryRegion   :  
--
CREATE TABLE City (
    cityName       NVARCHAR(100) NOT NULL,
    zipCode        NVARCHAR(100) NOT NULL UNIQUE,
    cityId         BIGINT NOT NULL UNIQUE,
    countryRegion  NVARCHAR(100) NOT NULL,
CONSTRAINT pk_City PRIMARY KEY CLUSTERED (cityName,zipCode,cityId,countryRegion))
GO

--
-- Create Table    : 'Address'   
-- streetAddress   :  
-- addressId       :  
-- cityId          :  (references City.cityId)
-- cityName        :  (references City.cityName)
-- zipCode         :  (references City.zipCode)
-- countryRegion   :  (references City.countryRegion)
--
CREATE TABLE Address (
    streetAddress  NVARCHAR(100) NOT NULL,
    addressId      BIGINT NOT NULL UNIQUE,
    cityId         BIGINT NOT NULL,
    cityName       NVARCHAR(100) NOT NULL,
    zipCode        NVARCHAR(100) NOT NULL,
    countryRegion  NVARCHAR(100) NOT NULL,
CONSTRAINT pk_Address PRIMARY KEY CLUSTERED (streetAddress,addressId),
CONSTRAINT fk_Address FOREIGN KEY (cityName,zipCode,cityId,countryRegion)
    REFERENCES City (cityName,zipCode,cityId,countryRegion)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Person'   
-- fullName        :  
-- personId        :  
-- streetAddress   :  (references Address.streetAddress)
-- personType      :  
-- addressId       :  (references Address.addressId)
--
CREATE TABLE Person (
    fullName       VARCHAR(100) NOT NULL,
    personId       BIGINT NOT NULL UNIQUE,
    streetAddress  NVARCHAR(100) NOT NULL,
    personType     BIGINT NOT NULL,
    addressId      BIGINT NOT NULL,
CONSTRAINT pk_Person PRIMARY KEY CLUSTERED (fullName,personId,personType),
CONSTRAINT fk_Person FOREIGN KEY (streetAddress,addressId)
    REFERENCES Address (streetAddress,addressId)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'ContactInfo'   
-- company         :  
-- phoneNumber     :  
-- fullName        :  (references Person.fullName)
-- contactId       :  
-- personId        :  (references Person.personId)
-- contactType     :  
-- personType      :  (references Person.personType)
--
CREATE TABLE ContactInfo (
    company        NVARCHAR(100) NOT NULL,
    phoneNumber    BIGINT NOT NULL UNIQUE,
    fullName       VARCHAR(100) NOT NULL,
    contactId      BIGINT NOT NULL UNIQUE,
    personId       BIGINT NOT NULL,
    contactType    NVARCHAR(100) NOT NULL,
    personType     BIGINT NOT NULL,
CONSTRAINT pk_ContactInfo PRIMARY KEY CLUSTERED (company,phoneNumber,contactId,contactType),
CONSTRAINT fk_ContactInfo FOREIGN KEY (fullName,personId,personType)
    REFERENCES Person (fullName,personId,personType)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'EmailAddress'   
-- email           :  
-- fullName        :  (references Person.fullName)
-- emailId         :  
-- personId        :  (references Person.personId)
-- personType      :  (references Person.personType)
--
CREATE TABLE EmailAddress (
    email          NVARCHAR(100) NOT NULL UNIQUE,
    fullName       VARCHAR(100) NULL,
    emailId        BIGINT NOT NULL UNIQUE,
    personId       BIGINT NULL,
    personType     BIGINT NULL,
CONSTRAINT pk_EmailAddress PRIMARY KEY CLUSTERED (email,emailId),
CONSTRAINT fk_EmailAddress FOREIGN KEY (fullName,personId,personType)
    REFERENCES Person (fullName,personId,personType)
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Note'   
-- noteId          :  
-- fullName        :  (references Person.fullName)
-- note            :  
-- personId        :  (references Person.personId)
-- personType      :  (references Person.personType)
--
CREATE TABLE Note (
    noteId         BIGINT NOT NULL UNIQUE,
    fullName       VARCHAR(100) NULL,
    note           NVARCHAR(100) NOT NULL,
    personId       BIGINT NULL,
    personType     BIGINT NULL,
CONSTRAINT pk_Note PRIMARY KEY CLUSTERED (noteId),
CONSTRAINT fk_Note FOREIGN KEY (fullName,personId,personType)
    REFERENCES Person (fullName,personId,personType)
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'AA'   
-- fullName        :  (references Person.fullName)
-- personId        :  (references Person.personId)
-- streetAddress   :  (references Address.streetAddress)
-- addressId       :  (references Address.addressId)
-- personType      :  (references Person.personType)
-- addressType     :  
-- altAddressId    :  
--
CREATE TABLE AA (
    fullName       VARCHAR(100) NOT NULL,
    personId       BIGINT NOT NULL,
    streetAddress  NVARCHAR(100) NOT NULL,
    addressId      BIGINT NOT NULL,
    personType     BIGINT NOT NULL,
    addressType    NVARCHAR(100) NOT NULL,
    altAddressId   BIGINT NOT NULL UNIQUE,
CONSTRAINT pk_AA PRIMARY KEY CLUSTERED (fullName,personId,streetAddress,addressId,personType,addressType,altAddressId),
CONSTRAINT fk_AA FOREIGN KEY (fullName,personId,personType)
    REFERENCES Person (fullName,personId,personType)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
--CONSTRAINT fk_AA2 FOREIGN KEY (streetAddress,addressId)
--    REFERENCES Address (streetAddress,addressId)
--    ON DELETE CASCADE
--    ON UPDATE CASCADE
)
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON City TO public
GO
GRANT ALL ON Address TO public
GO
GRANT ALL ON Person TO public
GO
GRANT ALL ON ContactInfo TO public
GO
GRANT ALL ON EmailAddress TO public
GO
GRANT ALL ON Note TO public
GO
GRANT ALL ON AA TO public
GO

